variables:
  PLAN: "plan.tfplan"
  PLAN_JSON: "plan.json"
  TF_VERSION: "0.13.7"
  TF_IN_AUTOMATION: "true"
  TF_ROOT: "${CI_PROJECT_DIR}"
  TF_STATE_NAME: "default"
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: "${CI_JOB_TOKEN}"
  TF_ENVIRONMENTS: [staging,production]

include:
  remote: 'https://raw.githubusercontent.com/caiohasouza/testdockerregistry2/master/gitlab/terraform/base.yaml'

image:
  name: hashicorp/terraform:$TF_VERSION
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - plan
  - apply

validate:
  extends: .validate

plan:
  extends: .plan
  variables:
    ROLE_ARN: "${AWS_ROLE_ARN}-readOnly"

apply:
  extends: .apply
  variables:
    ROLE_ARN: "${AWS_ROLE_ARN}"
  dependencies:
    - plan